# Generated by Django 4.1.6 on 2023-04-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_is_top_product_is_banner_product_banner_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_exchange_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='exchange_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
