# Generated by Django 4.1.6 on 2023-12-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
