# Generated by Django 4.1.6 on 2024-02-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerDeco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='banner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'banner_deco',
            },
        ),
    ]
