# Generated by Django 4.0.3 on 2022-06-21 14:07

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('PERSONAL_GENDER', models.CharField(blank=True, max_length=10, null=True)),
                ('PERSONAL_PROFESSION', models.CharField(blank=True, max_length=100, null=True)),
                ('PERSONAL_WWW', models.CharField(blank=True, max_length=100, null=True)),
                ('PERSONAL_BIRTHDAY', models.CharField(blank=True, max_length=100, null=True)),
                ('PERSONAL_ICQ', models.CharField(blank=True, max_length=100, null=True)),
                ('PERSONAL_PHONE', models.CharField(blank=True, max_length=20, null=True)),
                ('PERSONAL_FAX', models.CharField(blank=True, max_length=100, null=True)),
                ('PERSONAL_MOBILE', models.CharField(blank=True, max_length=100, null=True)),
                ('PERSONAL_PAGER', models.CharField(blank=True, max_length=100, null=True)),
                ('PERSONAL_STREET', models.CharField(blank=True, max_length=100, null=True)),
                ('PERSONAL_CITY', models.CharField(blank=True, max_length=100, null=True)),
                ('PERSONAL_STATE', models.CharField(blank=True, max_length=100, null=True)),
                ('PERSONAL_ZIP', models.CharField(blank=True, max_length=100, null=True)),
                ('PERSONAL_COUNTRY', models.CharField(blank=True, max_length=100, null=True)),
                ('WORK_COMPANY', models.CharField(blank=True, max_length=100, null=True)),
                ('WORK_POSITION', models.CharField(blank=True, max_length=100, null=True)),
                ('WORK_PHONE', models.CharField(blank=True, max_length=100, null=True)),
                ('UF_DEPARTMENT', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), size=None)),
                ('UF_INTERESTS', models.CharField(blank=True, max_length=100, null=True)),
                ('UF_SKILLS', models.CharField(blank=True, max_length=100, null=True)),
                ('UF_WEB_SITES', models.CharField(blank=True, max_length=100, null=True)),
                ('UF_XING', models.CharField(blank=True, max_length=100, null=True)),
                ('UF_LINKEDIN', models.CharField(blank=True, max_length=100, null=True)),
                ('UF_FACEBOOK', models.CharField(blank=True, max_length=100, null=True)),
                ('UF_TWITTER', models.CharField(blank=True, max_length=100, null=True)),
                ('UF_SKYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('UF_DISTRICT', models.CharField(blank=True, max_length=100, null=True)),
                ('UF_PHONE_INNER', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
