# Generated by Django 4.0.3 on 2022-08-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='unique_name',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=15),
        ),
    ]
