# Generated by Django 4.1.6 on 2024-02-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_websitevisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitevisitor',
            name='remote_address',
            field=models.CharField(max_length=100),
        ),
    ]
