# Generated by Django 4.1.6 on 2024-02-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_websitevisitor_remote_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitevisitor',
            name='remote_address',
            field=models.CharField(max_length=300),
        ),
    ]
