# Generated by Django 4.1.6 on 2024-02-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_websitevisitor_remote_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitevisitor',
            old_name='remote_address',
            new_name='visitor_id',
        ),
    ]
