# Generated by Django 4.1.6 on 2023-12-13 19:35

from django.db import migrations, models
import employee.models.contact


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.JSONField(blank=True, default=employee.models.contact.default_json, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.JSONField(blank=True, default=employee.models.contact.default_json, null=True),
        ),
    ]
