apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-depl
  name: nginx-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-depl
  template: # template for pod
    metadata:
      labels:
        app: nginx-depl
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 8080